// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bautogkxgukyikwuoiju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdXRvZ2t4Z3VreWlrd3VvaWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMTgzNTEsImV4cCI6MjA2NTc5NDM1MX0.KFvezXTAMiJ3sT2iY9fF89GCJ01EgAaO1wpq3aSAkBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);