-- Update subscription plans with actual Stripe price IDs
-- Generated by npm run setup:stripe

-- Update Starter plan
UPDATE subscription_plans SET
  stripe_monthly_price_id = 'price_1RdUeQ4gS1asmQHvGPY9YRg7',
  stripe_yearly_price_id = 'price_1RdUeR4gS1asmQHvWVIQ8ls2'
WHERE slug = 'starter';

-- Update Professional plan  
UPDATE subscription_plans SET
  stripe_monthly_price_id = 'price_1RdUeR4gS1asmQHvZqyHeSV4',
  stripe_yearly_price_id = 'price_1RdUeR4gS1asmQHvqClBedBj'
WHERE slug = 'professional';

-- Update Enterprise plan
UPDATE subscription_plans SET
  stripe_monthly_price_id = 'price_1RdUeS4gS1asmQHvZ4chuHt0',
  stripe_yearly_price_id = 'price_1RdUeS4gS1asmQHvx92bIilo'
WHERE slug = 'enterprise';

-- Verify the updates
SELECT 
  name,
  slug,
  price_monthly,
  price_yearly,
  stripe_monthly_price_id,
  stripe_yearly_price_id
FROM subscription_plans
ORDER BY sort_order; 